services:
  nacos:
    image: nacos/nacos-server
    platform: linux/amd64
    ports:
      - 8848:8848
    environment:
      - MODE=standalone

  mysql:
    image: mysql:8.3.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: echo

  redis:
    image: redis:latest
    ports:
      - 6379:6379
